### ISSUE TITLE
SQL error when using the search function (can't find FULLTEXT index matching the column list)

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica-directory#61]
When I try to search for users e.g. `https://dir.libranet.de/search?q=Batman` I get an error page with `Slim Application Error 
A website error has occurred. Sorry for the temporary inconvenience.`

The stack trace in app.log is:

```
[27-Sep-2020 08:18:58 UTC] Slim Application Error:
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list
File: .../vendor/atlas/pdo/src/Connection.php
Line: 138
Trace: #0 .../vendor/atlas/pdo/src/Connection.php(138): PDOStatement->execute()
#1 .../vendor/atlas/pdo/src/Connection.php(186): Atlas\Pdo\Connection->perform()
#2 .../src/classes/Views/Widget/AccountTypeTabs.php(44): Atlas\Pdo\Connection->fetchAll()
#3 .../src/classes/Controllers/Web/Search.php(80): Friendica\Directory\Views\Widget\AccountTypeTabs->render()
#4 .../src/classes/Routes/Web/BaseRoute.php(39): Friendica\Directory\Controllers\Web\Search->render()
#5 .../src/routes.php(22): Friendica\Directory\Routes\Web\BaseRoute->__invoke()
#6 [internal function]: Closure->{closure}()
#7 .../vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#8 .../vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#9 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
#10 .../vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#11 .../vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#12 .../vendor/gofabian/negotiation-middleware/src/NegotiationMiddleware.php(81): Slim\App->__invoke()
#13 [internal function]: Gofabian\Negotiation\NegotiationMiddleware->__invoke()
#14 .../vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#15 [internal function]: Slim\DeferredCallable->__invoke()
#16 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#17 .../vendor/boronczyk/localization-middleware/src/LocalizationMiddleware.php(166): Slim\App->Slim\{closure}()
#18 [internal function]: Boronczyk\LocalizationMiddleware->__invoke()
#19 .../vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#20 [internal function]: Slim\DeferredCallable->__invoke()
#21 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#22 .../src/classes/Middleware/ZrlMiddleware.php(38): Slim\App->Slim\{closure}()
#23 [internal function]: Friendica\Directory\Middleware\ZrlMiddleware->__invoke()
#24 .../vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#25 [internal function]: Slim\DeferredCallable->__invoke()
#26 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#27 .../vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#28 .../vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#29 .../vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#30 .../public/index.php(36): Slim\App->run()
#31 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
``` 

Latest version from stable. DB version is 8 (database schema migrated to version 8).

**Comment by AlfredSK** [comment]
From the migration script 'migrations/up/0008':

`ALTER TABLE `profile` ADD FULLTEXT KEY `profile-ft` (`name`, `pdesc`, `username`, `locality`, `region`, `country`);`

> ADD FULLTEXT KEY
KEY? Is that correct?

**Comment by AlfredSK** [comment]
Discussion: https://forum.friendi.ca/display/c443a55c-185f-7007-949c-a6f574289000 and the subsequent comments.

**Comment by AlfredSK** [comment]
Works again. Thank you!
