### ISSUE TITLE
Error msg in app.log

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica-directory#72]
I get lots of error messages like this in the app.log. what's going? 

```
2020-10-27 11:56:16 - ERROR {"uid":"687192a"}: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `friendica-directory`.`profile`.`available` at row 1:
#0 /var/www/directory/vendor/atlas/pdo/src/Connection.php(138): PDOStatement->execute()
#1 /var/www/directory/src/classes/Pollers/Profile.php(248): Atlas\Pdo\Connection->perform('INSERT INTO `pr...', Array)
#2 /var/www/directory/src/classes/Controllers/Cron.php(203): Friendica\Directory\Pollers\Profile->__invoke('https://soc.vis...')
#3 /var/www/directory/src/classes/Controllers/Cron.php(79): Friendica\Directory\Controllers\Cron->pollProfiles(58)
#4 /var/www/directory/bin/cron.php(22): Friendica\Directory\Controllers\Cron->execute()
#5 {main} []
```

All tables in that db are `utf8mb4_general_ci` collation. Have I misconfigured something?

**Comment by MrPetovan** [comment]
You do not, it just means we're trying to save an empty string in an integer field, which MySQL rightfully rejects.

**Comment by AndyHee** [comment]
Thanks for shedding light on this so swiftly @MrPetovan !
